cleared out html files and updates README
cavineers/ScoutingApp-GEN pull request #3
Opened 2023-12-11 13:19 UTC by PalaceLad

Changed the location of html files that will be used in future years to be in "currentyear" instead of 2023. Removed bloat files that are not being used anymore such as compselect.html or qr code files. Put recurring css content into one file. Updated readme to include Apple users. Removed mentions of 2023 and pit related content. Added a funny lil secret for max :)

2023-12-11 13:46 UTC, LuigisLuigi requested changes
change the cubes and cones in scout.js to literally anything else, not anything, you know what I mean. after that, it all looks great and I'll approve it

2023-12-11 13:46 UTC, LuigisLuigi commented on names.txt
??????????? what are those names???

2023-12-11 13:46 UTC, LuigisLuigi commented on static/2023/js/qrcode.js
😢

2023-12-11 13:46 UTC, LuigisLuigi commented on static/css/commons.css
very good, i love this ⭐

2023-12-11 13:46 UTC, LuigisLuigi commented on static/currentyear/js/scout.js
change the cones and cubes to something else, just not that because it'll be different every year

2023-12-11 14:57 UTC, PalaceLad commented on names.txt
one piece

2024-01-05 18:41 UTC, LuigisLuigi approved these changes

2024-01-08 17:24 UTC, merged